# Generated by Django 3.1.4 on 2020-12-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('Nome', models.CharField(help_text='Nome do Equipamento', max_length=50)),
                ('Setor', models.CharField(help_text='Setor do Equipamento', max_length=50)),
                ('Fabricante', models.CharField(help_text='Fabricante do Equipamento', max_length=50)),
            ],
            bases=('core.base',),
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('Nome', models.CharField(max_length=50, verbose_name='Nome do Manutentor')),
                ('funcao', models.CharField(choices=[('eletric', 'Eletricista'), ('macanic', 'Mecânico'), ('lub', 'Lubrificador'), ('aut', 'Automação'), ('refri', 'Refrigeração'), ('aux_eletric', 'Auxiliar Eletricista'), ('aux_mecanic', 'Auxiliar Mecânico'), ('aux_refri', 'Auxiliar Refrigeração')], default='eletric', max_length=25, verbose_name='Função do Manutentor')),
            ],
            bases=('core.base',),
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modificado', models.DateTimeField(auto_now=True)),
                ('Solicitante', models.CharField(help_text='Solicitante da Ordem', max_length=50)),
                ('Tipo_Servico', models.CharField(help_text='Tipo do Serviço', max_length=50)),
                ('Descricao', models.TextField()),
                ('Setor', models.CharField(help_text='Setor do Serviço', max_length=50)),
                ('Causa', models.TextField(blank=True, help_text='Causa do Problema', null=True)),
                ('Realizado', models.TextField(blank=True, help_text='Serviço Realizado', null=True)),
                ('Situacao', models.CharField(choices=[('concluido', 'Serviço Concluido'), ('andamento', 'Serviço em Andamento'), ('cancelado', 'Serviço Cancelado'), ('suspenso', 'Serviço Suspenso'), ('aguardando', 'Arguardando Manutenção'), ('peca', 'Aguardando Peça'), ('atendimento', 'Em Atendimento')], default='aguardando', max_length=25, verbose_name='Situação do Serviço')),
                ('Estado', models.CharField(choices=[('Parado', 'Equipamento Parado'), ('Funcionando', 'Equipamento Funcionando'), ('Programado', 'Serviço Programado'), ('Melhoria', 'Serviço de Melhoria')], default='Parado', max_length=25, verbose_name='Estado do Equipamento')),
                ('Inicio_servico', models.DateTimeField()),
                ('Termino_servico', models.DateTimeField()),
                ('Equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamentos')),
                ('Manutentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.manutencao')),
            ],
        ),
        migrations.CreateModel(
            name='AbrirOrdem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('Solicitante', models.CharField(help_text='Solicitante da Ordem', max_length=50)),
                ('Tipo_Servico', models.CharField(help_text='Tipo do Serviço', max_length=50)),
                ('Descricao', models.TextField()),
                ('Setor', models.CharField(help_text='Setor do Serviço', max_length=50)),
                ('Situacao', models.CharField(choices=[('concluido', 'Serviço Concluido'), ('andamento', 'Serviço em Andamento'), ('cancelado', 'Serviço Cancelado'), ('suspenso', 'Serviço Suspenso'), ('aguardando', 'Arguardando Manutenção'), ('peca', 'Aguardando Peça')], default='aguardando', max_length=25, verbose_name='Situação do Serviço')),
                ('Equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamentos')),
            ],
        ),
    ]
