# Generated by Django 3.1.4 on 2021-01-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='Obs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abrirordem',
            name='Situacao',
            field=models.CharField(choices=[('concluido', 'Serviço Concluido'), ('andamento', 'Serviço em Andamento'), ('cancelado', 'Serviço Cancelado'), ('aguardando', 'Arguardando Manutenção'), ('peca', 'Aguardando Peça')], default='aguardando', max_length=25, verbose_name='Situação do Serviço'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='Estado',
            field=models.CharField(choices=[('Parado', 'Equipamento Parado'), ('Funcionando', 'Equipamento Funcionando')], default='Parado', max_length=25, verbose_name='Estado do Equipamento'),
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('obs', models.TextField()),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ordem')),
            ],
        ),
    ]
