# Generated by Django 3.1.4 on 2021-01-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210105_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almoxarifado',
            name='Minimo',
            field=models.IntegerField(help_text='Estoque Minimo'),
        ),
    ]
