# Generated by Django 3.1.4 on 2021-09-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210105_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('estado', models.CharField(max_length=10)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.equipamentos')),
            ],
            bases=('core.base',),
        ),
    ]
