# Generated by Django 3.1.4 on 2021-01-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201229_1329'),
        ('core', '0002_auto_20210105_0911'),
    ]

    operations = [
    ]
