# Generated by Django 3.1.4 on 2020-12-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201219_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('Nome', models.CharField(help_text='Nome do Equipamento', max_length=50)),
                ('Setor', models.CharField(help_text='Setor do Equipamento', max_length=50)),
                ('Fabricante', models.CharField(help_text='Fabricante do Equipamento', max_length=50)),
            ],
            bases=('core.base',),
        ),
    ]
