# Generated by Django 3.1.4 on 2021-01-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20210105_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='Pecas',
            field=models.ManyToManyField(blank=True, null=True, to='core.Almoxarifado'),
        ),
    ]
