# Generated by Django 3.1.4 on 2020-12-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_equipamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FecharOrdem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modificado', models.DateTimeField(auto_now=True)),
                ('Solicitante', models.CharField(help_text='Solicitante da Ordem', max_length=50)),
                ('Tipo_Servico', models.CharField(help_text='Tipo do Serviço', max_length=50)),
                ('Descricao', models.TextField()),
                ('Setor', models.CharField(help_text='Setor do Serviço', max_length=50)),
                ('Causa', models.TextField(help_text='Causa do Problema')),
                ('Realizado', models.TextField(help_text='Serviço Realizado')),
                ('Situacao', models.CharField(choices=[('concluido', 'Serviço Concluido'), ('andamento', 'Serviço em Andamento'), ('cancelado', 'Serviço Cancelado'), ('suspenso', 'Serviço Suspenso'), ('aguardando', 'Arguardando Manutenção'), ('peca', 'Aguardando Peça')], default='aguardando', max_length=25, verbose_name='Situação do Serviço')),
                ('Equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamentos')),
                ('Manutentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manutencao')),
            ],
        ),
        migrations.CreateModel(
            name='AbrirOrdem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('Solicitante', models.CharField(help_text='Solicitante da Ordem', max_length=50)),
                ('Tipo_Servico', models.CharField(help_text='Tipo do Serviço', max_length=50)),
                ('Descricao', models.TextField()),
                ('Setor', models.CharField(help_text='Setor do Serviço', max_length=50)),
                ('Situacao', models.CharField(choices=[('concluido', 'Serviço Concluido'), ('andamento', 'Serviço em Andamento'), ('cancelado', 'Serviço Cancelado'), ('suspenso', 'Serviço Suspenso'), ('aguardando', 'Arguardando Manutenção'), ('peca', 'Aguardando Peça')], default='aguardando', max_length=25, verbose_name='Situação do Serviço')),
                ('Equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamentos')),
            ],
        ),
    ]
