# Generated by Django 3.1.4 on 2020-12-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201221_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='Abertura_servico',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='Tipo_Servico',
            field=models.CharField(choices=[('Corretivo', 'Serviço Corretivo'), ('Preventivo', 'Serviço Preventivo'), ('Inspecao', 'Serviço de Inpeção'), ('Melhoria', 'Serviço de Melhoria')], default='Corretivo', max_length=25, verbose_name='Tipo do Serviço'),
        ),
    ]
