# Generated by Django 3.1.4 on 2020-12-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_abrirordem_fecharordem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FecharOrdem',
            new_name='Ordem',
        ),
    ]
