# Generated by Django 3.1.4 on 2020-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201219_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='Situacao',
            field=models.CharField(choices=[('concluido', 'Serviço Concluido'), ('andamento', 'Serviço em Andamento'), ('cancelado', 'Serviço Cancelado'), ('suspenso', 'Serviço Suspenso'), ('aguardando', 'Arguardando Manutenção'), ('peca', 'Aguardando Peça'), ('atendimento', 'Em Atendimento')], default='aguardando', max_length=25, verbose_name='Situação do Serviço'),
        ),
    ]
