# Generated by Django 3.1.4 on 2021-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_maquinas_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinas',
            name='Ordem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
