# Generated by Django 3.1.4 on 2020-12-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_almoxarifado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almoxarifado',
            name='Preco',
            field=models.FloatField(help_text='Valor da Peça', max_length=10),
        ),
    ]
