# Generated by Django 3.1.4 on 2020-12-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201219_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='Causa',
            field=models.TextField(blank=True, help_text='Causa do Problema', null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='Manutentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.manutencao'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='Realizado',
            field=models.TextField(blank=True, help_text='Serviço Realizado', null=True),
        ),
    ]
