# Generated by Django 3.1.4 on 2020-12-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201221_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='almoxarifado',
            name='Minimo',
            field=models.CharField(default=1, help_text='Estoque Minimo', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almoxarifado',
            name='Qto',
            field=models.IntegerField(default=1, help_text='Quantidade de Peças em Estoque', max_length=2),
            preserve_default=False,
        ),
    ]
