# Generated by Django 3.1.4 on 2020-12-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201221_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='Pecas',
            field=models.ManyToManyField(to='core.Almoxarifado'),
        ),
    ]
