# Generated by Django 3.1.4 on 2020-12-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ordem_pecas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='Pecas',
            field=models.ManyToManyField(blank=True, null=True, to='core.Almoxarifado'),
        ),
    ]
