# Generated by Django 3.1.4 on 2020-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201221_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='Modificado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
