# Generated by Django 3.1.4 on 2020-12-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201221_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almoxarifado',
            name='Qto',
            field=models.IntegerField(help_text='Quantidade de Peças em Estoque'),
        ),
    ]
