# Generated by Django 3.1.4 on 2020-12-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201222_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='Pecas',
            field=models.ManyToManyField(blank=True, to='core.Almoxarifado'),
        ),
    ]
